## Pyravelry

---

Pyravelry is a Python library for interacting with the Ravelry API. This notebook will show the basics for how to interact with the library.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pyravelry import Client, Settings

In [3]:
# need to define a .env with RAVELRY_USERNAME and RAVELRY_API_KEY
# or define it on the command line.
settings = Settings()
client = Client(settings=settings)

## Getting data

Data from an API call is cached by default (using [hishel](https://hishel.com/1.0/)). The data is returned as a pydantic model, but it can be converted to `pandas` or `polars` dataframes using properties of the custom `ravelry.models.base.BaseRavelryModel` pydantic model.

In [8]:
results = client.search.query(query="merino", limit=50, types=["Yarn"])

In [9]:
results.pandas.head()

,title,type_name,caption,tiny_image_url,image_url,record.type,record.id,record.permalink,record.uri
0,MerinoSeide,yarn,,https://images4-f.ravelrycache.com/uploads/Sid...,https://images4-g.ravelrycache.com/uploads/Sid...,Yarn,123711,sidispinnt-merinoseide,/yarns/library/sidispinnt-merinoseide.json
1,Merinosukka,yarn,,https://images4-g.ravelrycache.com/uploads/ell...,https://images4-g.ravelrycache.com/uploads/ell...,Yarn,186156,silmukka-merinosukka,/yarns/library/silmukka-merinosukka.json
2,MERINO100,yarn,,https://images4-g.ravelrycache.com/uploads/Vic...,https://images4-g.ravelrycache.com/uploads/Vic...,Yarn,201437,vickevira-merino100,/yarns/library/vickevira-merino100.json
3,Merino-Tussah,yarn,,https://images4-g.ravelrycache.com/uploads/ann...,https://images4-f.ravelrycache.com/uploads/ann...,Yarn,234648,bunte-wolle-merino-tussah,/yarns/library/bunte-wolle-merino-tussah.json
4,Merinosilke,yarn,,https://images4-g.ravelrycache.com/uploads/eva...,https://images4-f.ravelrycache.com/uploads/eva...,Yarn,60840,stakets-hantverk--design-merinosilke,/yarns/library/stakets-hantverk--design-merino...

In [10]:
results.polars.head()

shape: (5, 9)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ title      ┆ type_name ┆ caption ┆ tiny_imag ┆ … ┆ record.ty ┆ record.id ┆ record.pe ┆ record.ur │
│ ---        ┆ ---       ┆ ---     ┆ e_url     ┆   ┆ pe        ┆ ---       ┆ rmalink   ┆ i         │
│ str        ┆ str       ┆ str     ┆ ---       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ ---       │
│            ┆           ┆         ┆ str       ┆   ┆ str       ┆           ┆ str       ┆ str       │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ MerinoSeid ┆ yarn      ┆         ┆ https://i ┆ … ┆ Yarn      ┆ 123711    ┆ sidispinn ┆ /yarns/li │
│ e          ┆           ┆         ┆ mages4-f. ┆   ┆           ┆           ┆ t-merinos ┆ brary/sid │
│            ┆           ┆         ┆ ravelryca ┆   ┆           ┆           ┆ eide      ┆ ispinnt-m │
│            ┆           ┆         ┆ che…      ┆   ┆           ┆           ┆           ┆ eri…      │
│ Merinosukk ┆ yarn      ┆         ┆ https://i ┆ … ┆ Yarn      ┆ 186156    ┆ silmukka- ┆ /yarns/li │
│ a          ┆           ┆         ┆ mages4-g. ┆   ┆           ┆           ┆ merinosuk ┆ brary/sil │
│            ┆           ┆         ┆ ravelryca ┆   ┆           ┆           ┆ ka        ┆ mukka-mer │
│            ┆           ┆         ┆ che…      ┆   ┆           ┆           ┆           ┆ ino…      │
│ MERINO100  ┆ yarn      ┆         ┆ https://i ┆ … ┆ Yarn      ┆ 201437    ┆ vickevira ┆ /yarns/li │
│            ┆           ┆         ┆ mages4-g. ┆   ┆           ┆           ┆ -merino10 ┆ brary/vic │
│            ┆           ┆         ┆ ravelryca ┆   ┆           ┆           ┆ 0         ┆ kevira-me │
│            ┆           ┆         ┆ che…      ┆   ┆           ┆           ┆           ┆ rin…      │
│ Merino-Tus ┆ yarn      ┆         ┆ https://i ┆ … ┆ Yarn      ┆ 234648    ┆ bunte-wol ┆ /yarns/li │
│ sah        ┆           ┆         ┆ mages4-g. ┆   ┆           ┆           ┆ le-merino ┆ brary/bun │
│            ┆           ┆         ┆ ravelryca ┆   ┆           ┆           ┆ -tussah   ┆ te-wolle- │
│            ┆           ┆         ┆ che…      ┆   ┆           ┆           ┆           ┆ mer…      │
│ Merinosilk ┆ yarn      ┆         ┆ https://i ┆ … ┆ Yarn      ┆ 60840     ┆ stakets-h ┆ /yarns/li │
│ e          ┆           ┆         ┆ mages4-g. ┆   ┆           ┆           ┆ antverk-- ┆ brary/sta │
│            ┆           ┆         ┆ ravelryca ┆   ┆           ┆           ┆ design-me ┆ kets-hant │
│            ┆           ┆         ┆ che…      ┆   ┆           ┆           ┆ rin…      ┆ ver…      │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
results = client.people.show(username="cltheuer")

In [14]:
results.pandas.T

                             0
id                    13988848
username              cltheuer
tiny_photo_url            None
small_photo_url           None
photo_url                 None
large_photo_url           None
profile_country_code      None
first_name                None
about_me                  None
about_me_html             None
fave_colors               None
fave_curse                None
location
pattern_author            None
user_sites                  []